### ISSUE TITLE
Add flag to treat warnings as errors

### ISSUE THREAD

**Issue by Lupus** [amuletml/amulet#228]
Would be nice to be able to error out if there are any warnings.

**Comment by SquidDev** [comment]
It might also be worth having flags to disable/promote/demote individual warnings. We may want to give error messages string identifiers as well as numeric ones, so the command line args don't end up like OCaml's.

**Comment by Lupus** [comment]
Probably having analog of gcc's `-Werror` would be a good start, and later on can be expanded to `-Werror=foo` to enable fine-grained control.
