### ISSUE TITLE
Record types?

### ISSUE THREAD

**Issue by Lupus** [amuletml/amulet#229]
Are there any plans to support record types? Currently records are only possible in variants, not as something first class.

**Comment by SquidDev** [comment]
Amulet uses polymorphic rows/records, so it should be possible to declare one as a type alias:


```ml
type person <- { name : string, age : int }
```

**Comment by zardyh** [comment]
Or have it be inferred by in a function parameter.

**Comment by Lupus** [comment]
Oh, cool! Would be awesome to have some more documentation on the language :)

**Comment by SquidDev** [comment]
I think we'll all agree on that one :). It's definitely something we're aware of, just a matter of planning and writing docs. If there's anything else you feel could be clarified, it would be good to know!
