### ISSUE TITLE
How to define ordering for custom type?

### ISSUE THREAD

**Issue by Lupus** [amuletml/amulet#235]
I'm trying to define ordering on my type inside of my module like this:

```ocaml
instance ord (string * json) begin
  let (n1, _) < (n2, _)  = n1 < n2
  let (n1, _) <= (n2, _) = n1 <= n2
  let (n1, _) > (n2, _)  = n1 > n2
  let (n1, _) >= (n2, _)  = n1 >= n2
end
```

But compiler complains:

```
json.ml[15:1 ..20:3]: error (E2028)
   │
15 │ instance ord (string * json) begin
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  This instance should be defined in the same module as ord

The following message has a detailed explanation: 2028.
Try 'amc explain 2028' to see it.
```

Explanation suggests that I can not do that without modification of stdlib?

**Comment by SquidDev** [comment]
Yep. Basically the "orphan restriction" means such instances are illegal. Otherwise you could write overlapping instances such as this:

```ml
instance ord (string * 'a)
  let ord = ...

instance ord ('a * json)
  let ord = ...
``

`amc explain 2028` goes into a little more detail, but instead, you should wrap everything in a new type:

```ml
type json_key = JsonKey of string * json
instance ord json_key
  let ord (JsonKey (k, _)) (JsonKey (k', _)) = k `compare` k'
```

**Comment by Lupus** [comment]
May be this suggestion could be baked into `amc explain 2028`? It's not immediately obvious what one should do instead.

So far I designed it in old-school style, by passing compare function explicitly to my list sorting function. I'll try more advance approach one day, thanks! :)
