### ISSUE TITLE
amulet-lsp is not part of release tarball

### ISSUE THREAD

**Issue by Lupus** [amuletml/amulet#236]
It seems that amulet-lsp is not build into the release tarball. Is that intended?

**Comment by zardyh** [comment]
If you mean GitHub releases: Yes. It wasn't around by the time of the last release.
If you mean Jenkins builds: No, that's a bug.

**Comment by zardyh** [comment]
`amulet-lsp` is in the Jenkins nightly tarballs and will be in the GitHub release tarballs when we actually make a release that could contain amulet-lsp without violating the laws of causality.
