### ISSUE TITLE
Will an either type be added?

### ISSUE THREAD

**Issue by davidgarland** [amuletml/amulet#240]
I think having the `either` type would be rather nifty (there's already a working definition in `examples`), but I'm curious as to whether this is regarded as not idiomatic because the exception system is present.

**Comment by zardyh** [comment]
`either` and exceptions are not mutually exclusive. I'd be happy to merge a PR adding a canonical sum type.

**Comment by davidgarland** [comment]
Workin' on that now-- another quick question, how does one do multiple typeclass constraints? I tried `(eq 'a, eq 'b) => ...`, `eq 'a, eq 'b => ...`, `eq ('a, 'b) => ...`, and `eq 'a => eq 'b => ...` and none of those seemed to work when defining an instance-- so I'm not sure how to define an `eq` instance for `either`, as it has two types which I need to constrain.

**Comment by davidgarland** [comment]
Oh wait, `(eq 'a * eq 'b)` works, I forgot that the type constructor for `(a, b)` was `a * b`-- sorry!

**Comment by davidgarland** [comment]
Fixed by https://github.com/amuletml/amulet/pull/241.
