### ISSUE TITLE
Symbol clashes in generated code

### ISSUE THREAD

**Issue by Lupus** [amuletml/amulet#249]
I have the following external defined:

```ocaml
  external val encode_i : int -> string = "function (x) return string.format(\"0x%016x\", x) end"
```

Amulet was smart enough to inline it in generated code like this:

```lua
local tmp2 = string.format("0x%016x", 0)
```

But there is a value named `string` somewhere up the Lua call graph. I have the following runtime error as result:

```
attempt to index a function value (upvalue 'string')
```

I can probably work around this by accessing this function as `_G["string"].format`, but there should be some systematic solution to such issues.

**Comment by zardyh** [comment]
@SquidDev Easy solution: add the Lua built-in tables to the keyword set. I'll see what I can do

**Comment by Lupus** [comment]
May be mangling variables that shadow built-in values in specific backend will be better option? You will put the burden of knowing the union of keywords (including potentially all of stdlib modules) used in all backends to the user.
