### ISSUE TITLE
Type error for (**) upon opening the REPL

### ISSUE THREAD

**Issue by davidgarland** [amuletml/amulet#288]
![Imgur](https://i.imgur.com/mkM3dEv.png)

**Comment by davidgarland** [comment]
After taking a quick browse through, I think just changing this line should fix it:
https://github.com/amuletml/amulet/blob/65d82e1a18fbce74c0257498ab7f12e3112aea13/src/Syntax/Builtin.hs#L375

**Comment by SquidDev** [comment]
Thanks for the report, fixed in e02783ff56e9c5a75808f8f2893a8c1aeb480c1c. This really should have been caught by CI, but the build machine isn't especially happy right now.
