### ISSUE TITLE
Record type doc

### ISSUE THREAD

**Issue by sigmasoldi3r** [amuletml/amulet#303]
I've been looking for the [Records can be extended using magic.↩︎](https://abby.how/posts/2019-09-22.html) at https://amulet.works/tutorials/01-intro.html but the link is broken.

What is the current way to achieve it? There are join types like in Typescript?

```reason
type file <- { readAll : () -> string }
type response <- { anything : () -> string } & file
```

**Comment by SquidDev** [comment]
Ahh, that blog post is located at https://abby.how/quick/manipulating-records-in-amulet.html now. Woops, I'll update those links.

To answer your question, there's no intersection types in Amulet (as that implies subtyping). Instead you can do something like this:

```ocaml
type file <- { readAll : () -> string }
type response <- { file | anything : () -> string }
```

**Comment by SquidDev** [comment]
Links should now be fixed :).
